import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import {
  ClerkProvider,
  SignInButton,
  SignUpButton,
  SignedIn,
  SignedOut,
  UserButton,
} from "@clerk/nextjs";
import { Button } from "@/components/ui/button";
import { Card } from "@/components/ui/card";
import { Avatar, AvatarFallback } from "@/components/ui/avatar";
import { Badge } from "@/components/ui/badge";
import { Separator } from "@/components/ui/separator";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs";
import { Input } from "@/components/ui/input";
import { Brain, LineChart, Lightbulb, Check } from "lucide-react";
const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body
          className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        >
          <header className="fixed top-0 left-0 right-0 z-50 border-b border-slate-200/60 bg-white/95 backdrop-blur-xl shadow-sm">
            <div className="max-w-7xl mx-auto px-6 sm:px-8">
              <div className="flex items-center justify-between h-16">
                {/* Logo */}
                <div className="flex items-center gap-3">
                  <div className="w-9 h-9 rounded-xl bg-gradient-to-br from-indigo-600 via-indigo-500 to-violet-600 flex items-center justify-center shadow-lg shadow-indigo-500/40 ring-1 ring-indigo-400/20">
                    <Brain className="w-5 h-5 text-white" />
                  </div>
                  <span className="text-xl font-bold tracking-tight bg-gradient-to-r from-indigo-600 via-violet-600 to-indigo-600 bg-clip-text text-transparent">
                    EchoMind
                  </span>
                </div>

                {/* Navigation Links - Hidden on mobile */}
                <nav className="hidden md:flex items-center gap-8">
                  <a
                    href="#features"
                    className="text-sm font-medium text-slate-700 hover:text-indigo-600 transition-colors duration-200 relative after:absolute after:bottom-0 after:left-0 after:h-0.5 after:w-0 after:bg-indigo-600 after:transition-all after:duration-200 hover:after:w-full"
                  >
                    Features
                  </a>
                  <a
                    href="#how-it-works"
                    className="text-sm font-medium text-slate-700 hover:text-indigo-600 transition-colors duration-200 relative after:absolute after:bottom-0 after:left-0 after:h-0.5 after:w-0 after:bg-indigo-600 after:transition-all after:duration-200 hover:after:w-full"
                  >
                    How it works
                  </a>
                  <a
                    href="#testimonials"
                    className="text-sm font-medium text-slate-700 hover:text-indigo-600 transition-colors duration-200 relative after:absolute after:bottom-0 after:left-0 after:h-0.5 after:w-0 after:bg-indigo-600 after:transition-all after:duration-200 hover:after:w-full"
                  >
                    Testimonials
                  </a>
                </nav>

                {/* Auth Buttons */}
                <div className="flex items-center gap-3">
                  {/* If NOT signed in */}
                  <SignedOut>
                    <SignInButton mode="modal">
                      <Button
                        variant="ghost"
                        className="hidden sm:inline-flex h-10 px-5 rounded-full text-slate-700 hover:text-indigo-600 hover:bg-indigo-50/80 font-medium text-sm transition-all duration-200"
                      >
                        Sign in
                      </Button>
                    </SignInButton>

                    <SignUpButton mode="modal">
                      <Button className="h-10 px-6 rounded-full bg-gradient-to-r from-indigo-600 to-violet-600 hover:from-indigo-700 hover:to-violet-700 text-white font-medium text-sm shadow-lg shadow-indigo-600/40 hover:shadow-xl hover:shadow-indigo-600/50 transition-all duration-200">
                        Get started
                      </Button>
                    </SignUpButton>
                  </SignedOut>

                  {/* If signed in */}
                  <SignedIn>
                    <UserButton
                      appearance={{
                        elements: {
                          avatarBox:
                            "w-9 h-9 ring-2 ring-indigo-500/50 shadow-md",
                        },
                      }}
                    />
                  </SignedIn>
                </div>
              </div>
            </div>
          </header>

          <div className="pt-16">{children}</div>
        </body>
      </html>
    </ClerkProvider>
  );
}
